### ISSUE TITLE
어플리케이션 기획

### ISSUE THREAD

**Issue by jwKim1835** [201733cpb1/OurCompany#3]

**Comment by KimJoungWoo** [comment]
앱 기획입니다

**Comment by jjonghun1004** [comment]
My Love Pet 앱 구상도

![image](https://cloud.githubusercontent.com/assets/22736036/24345356/aeca77ae-130a-11e7-8d0d-f001338f1084.png)

**Comment by jjonghun1004** [comment]
My Love Pet 앱 구상도

변경된 사항: 메인화면 - 커뮤니티 - 세일정보 삭제

![image](https://cloud.githubusercontent.com/assets/22736036/24345401/f06fd3de-130a-11e7-93e6-76078db12573.png)

**Comment by jjonghun1004** [comment]
## 중고장터 기획 및 디자인 진행현황

저희 OurComapny에서는 My Love Pet의 중고장터를 "중고나라"앱을 모티브로 삼고 프로젝트를 기획 및 진행 할 예정입니다.


#### 기본적인 설계 및 디자인(Prototype) 




1.실행 시 첫화면


![1](https://cloud.githubusercontent.com/assets/22736036/24346203/5b7c938a-130e-11e7-8f51-52184f131a1d.png)







2.카테고리 설정화면


![2](https://cloud.githubusercontent.com/assets/22736036/24346280/8cc05026-130e-11e7-80f4-5924eb6fc53b.png)






3.중고물품 리스트(UI의 최하단에 배너 삽입 예정) - 이익창출효과


![3](https://cloud.githubusercontent.com/assets/22736036/24346283/8e08fcbc-130e-11e7-985b-ef1934d7cca4.png)




앞으로 해야할 일
1.카테고리를 어떻게 세분화하여 분류할 것인가
2.각 UI마다 레이아웃을 어떻게 설정할 것인가
3.물품 검색 기능의 구체화
4.Drag and drop 및 Scrollbar를 구현할 UI위치선정 및 방법의 모색

**Comment by jwKim1835** [comment]
![imgres](https://cloud.githubusercontent.com/assets/26519770/24347417/3941d5fa-1313-11e7-9d76-78966da2233f.jpg)
아주 좋소

**Comment by jjonghun1004** [comment]
# 중고장터 글쓰기 기능 

중고장터의 기능들 중 가장 중요한 글쓰기 기능에 대한 기획 및 UI 설계현황 입니다.

### 상품에 대한 정보

![2](https://cloud.githubusercontent.com/assets/22736036/24350529/79f1ab3e-131d-11e7-9596-cd468596ff32.png)





#### 판매자 정보에 들어갈 내용

-아이디
-이름
-전화번호
-이메일주소

### 글쓰기 버튼을 눌렀을때

if(개인정보수집란에 동의를 했을 경우)
{
중고장터에 판매글 올릴 수 있다.
}
else(동의를 하지 않았을 경우)
{
판매글 올릴 수 없다.
}


### 기본적인 UI

![default](https://cloud.githubusercontent.com/assets/22736036/24350639/ea6d947c-131d-11e7-9ddf-57c883c92ade.PNG)


#### 번호입력란을 제거하고 회원가입시 사용자 번호를 받게 변경



### 세부적인 구성

1.카테고리 선택 클릭시 카테고리 UI로 넘어간다.

![8cc05026-130e-11e7-80f4-5924eb6fc53b](https://cloud.githubusercontent.com/assets/22736036/24347326/eaa11c1c-1312-11e7-97a9-f96234280e93.png)

2.대표사진 선택시 

![default](https://cloud.githubusercontent.com/assets/22736036/24348911/51e7e91e-1318-11e7-8ffa-0516e5b0322b.PNG)

**Comment by jjonghun1004** [comment]
# Tip 게시판 디자인 및 기본설계

### 게시판의 목록 중 "지름/알뜰정보"는 중고장터와 동일한 부분이 많기때문에 조원끼리 상의 후 제외하였습니다. 

![3](https://cloud.githubusercontent.com/assets/22736036/24389989/d4471062-13c0-11e7-95c5-8376b18ed898.png)

## 1.Tip게시판 메인 UI

![6](https://cloud.githubusercontent.com/assets/22736036/24390092/76fa7fba-13c1-11e7-8dac-a6b960528807.png)

##### 1.추천기능을 두어 각 게시물마다 추천을 할 수 있도록 설계할 예정(조회수와 더불어서 인기 게시물을 확인 할 수 있도록 사용자에게 알림)
##### 2.중고장터의 메인화면과 마찬가지로 최하단에 배너를 두어 광고수익을 창출 할 예정


## 2.Tip 게시판의 글쓰기 기능(권한을 관리자에게 줄지, 모든 사용자에게 줄지 구상예정)

 
![7](https://cloud.githubusercontent.com/assets/22736036/24390200/3e82ada0-13c2-11e7-819e-28f0ddec44b1.png)

##### 1.사진을 올릴 수 있도록 설계 예정

## 3.Tip 게시판의 게시글 읽기

![8](https://cloud.githubusercontent.com/assets/22736036/24390236/8892fbc0-13c2-11e7-8d1d-a6de753dd141.png)

##### 1.일반사용자가 제목,작성자,작성일자,추천,조회수 확인가능 
##### 2.밑에 댓글 기능을 두어 커뮤니티 할 수 있도록 설계 예정
##### 3.댓글 확인은 스크롤바를 두거나 페이스북 형식으로 구현할 예정
##### 4.추천 버튼을 두어 게시글에 추천을 할 수 있도록 한다.

**Comment by jjonghun1004** [comment]
# 자가진단 기본 UI
#### My Love Pet 앱의 메인화면의 하단에 버튼이 위치

##### 1.3월27일 캡스톤프로젝트 발표일 이 "자가진단"부분에서 사용자들의 많은 질문(의문)이 발생했으며 그 질문들을 바탕으로 점진적으로 수정 및 재설계 해야 할 의무...
##### 2.강아지(고양이)의 대표적인 이상 증상을 토대로 문항을 작성
##### 3.문항 마다의 점수를 바탕으로 통계를 내서 현재 강아지의 상태를 파악
##### 4.강아지의 상태를 파악 후 병원으로 전화 연결 또는 사용자에게 반려동물의 상태를 인식시킴 
  
## 화면구성   

![1](https://cloud.githubusercontent.com/assets/22736036/24390462/06dfcdd6-13c4-11e7-8fbf-b5a6e1017260.png)

![2](https://cloud.githubusercontent.com/assets/22736036/24390463/06e0d050-13c4-11e7-860f-9e76f96d6730.png)

![3](https://cloud.githubusercontent.com/assets/22736036/24390464/06e2fd58-13c4-11e7-9af6-4643eb893b77.png)

**Comment by jjonghun1004** [comment]
# 탐색기능 - 주변 산책경로 및 병원 UI구상 및 디자인

#### 이 기능은 사용자들에게 주변에 반려견을 산책 시키기위한 장소가 있는지 그리고 아플때 근처에 동물병원이 있는지에 대한 정보를 GPS 및 지도를 이용하여 수집하여 제공합니다.


### 목록
  
![default](https://cloud.githubusercontent.com/assets/22736036/24395640/49016488-13db-11e7-91ba-cbec9d01871b.PNG)

#### 탐색기능에는 산책로 및 병원정보 두 가지가 있습니다.

## 주변산책경로 UI화면

#### 근처 공원에 대한 정보를 제공합니다.

![4](https://cloud.githubusercontent.com/assets/22736036/24395780/c19377e2-13db-11e7-8ce4-c68179504ccc.png)
![5](https://cloud.githubusercontent.com/assets/22736036/24395781/c1d67a06-13db-11e7-9463-0091920875d2.png)



## 주변병원 UI화면

#### 주변 병원에 대한 정보를 보여줍니다.그리고 앱에서 전화걸기 버튼을 누르면 바로 전화가 연결되도록 설계 할 예정 입니다.

![2](https://cloud.githubusercontent.com/assets/22736036/24395816/e4b9cb36-13db-11e7-8615-58f29d13c9a0.png)
![3](https://cloud.githubusercontent.com/assets/22736036/24395817/e4bb22b0-13db-11e7-8107-70623af307a4.png)

**Comment by jjonghun1004** [comment]
# OurComapny 개인정보수집 이용 동의서 양식입니다.

![8c91247c-13bd-11e7-81bf-59127fded6ff](https://cloud.githubusercontent.com/assets/22736036/24399186/e917edb0-13e6-11e7-904c-b8028624e01d.png)

*** 팝업 형태 구상 UI

기능 : "개인정보동의서 보기"를 누를시에만 동의서 양식을 사용자에게 보여준다.
펫시터 및 중고장터에서 사용할 예정입니다.
개인정보(이름,전화번호,이메일)은 회원가입시 사용자에게 입력받습니다.

**Comment by jjonghun1004** [comment]
# App 디자인 진행현황

### Intro 화면 및 로그인 환경


![1](https://cloud.githubusercontent.com/assets/22736036/24831771/ac2b9368-1cdb-11e7-8ea0-9e709b9a02d2.PNG)

### 회원가입 화면 및 메인화면 구성


![2](https://cloud.githubusercontent.com/assets/22736036/24831772/ac59645a-1cdb-11e7-86e3-42fe6867ca9a.PNG)

### 펫시터 


![3](https://cloud.githubusercontent.com/assets/22736036/24831788/f618f40c-1cdb-11e7-97fa-ee887bc919cd.png)
![4](https://cloud.githubusercontent.com/assets/22736036/24831789/f61b4b3a-1cdb-11e7-9b88-e074954b4c4b.png)

**Comment by JINAJUNG** [comment]
![festival](https://cloud.githubusercontent.com/assets/26480592/24836925/864e85aa-1d63-11e7-84fb-83bf5c72732c.png)
![default](https://cloud.githubusercontent.com/assets/26480592/24836923/86480752-1d63-11e7-8f20-7b3dddd6488d.png)
![_tip](https://cloud.githubusercontent.com/assets/26480592/24836924/8648b198-1d63-11e7-817a-8bec086dc040.png)
![_](https://cloud.githubusercontent.com/assets/26480592/24836926/864eb2d2-1d63-11e7-8000-a273134feb85.png)
![_](https://cloud.githubusercontent.com/assets/26480592/24836922/8639405a-1d63-11e7-91c6-946c6b17df4a.png)
![_](https://cloud.githubusercontent.com/assets/26480592/24836928/867a0860-1d63-11e7-982d-8622d47dc79b.png)
![default](https://cloud.githubusercontent.com/assets/26480592/24836929/8688a0dc-1d63-11e7-8e7b-2355263c26d3.png)
![default](https://cloud.githubusercontent.com/assets/26480592/24836927/8671dd2a-1d63-11e7-9953-1d9112e41770.png)
앱 게시판 아이콘 입니다.

**Comment by jinari123** [comment]
앱 메뉴 아이콘 입니다.

![default](https://cloud.githubusercontent.com/assets/26480592/24836961/fa9a5d94-1d63-11e7-92a3-b417b873f5aa.png)
펫시터

![default](https://cloud.githubusercontent.com/assets/26480592/24836945/b56ac34e-1d63-11e7-9173-ab5db0df3f26.png)
게시판

![_tip](https://cloud.githubusercontent.com/assets/26480592/24836948/c165c8d8-1d63-11e7-9f0c-cc75094116ef.png)
TIP

![_](https://cloud.githubusercontent.com/assets/26480592/24836950/ca0d8e6c-1d63-11e7-865a-3fd6849b1890.png)
중고

![default](https://cloud.githubusercontent.com/assets/26480592/24836951/d0fb7c5c-1d63-11e7-8e43-0d42c327f1c6.png)
탐색

![_](https://cloud.githubusercontent.com/assets/26480592/24836954/d63032a8-1d63-11e7-95fa-6b62b0abbb51.png)
병원

![_](https://cloud.githubusercontent.com/assets/26480592/24836956/dabf588a-1d63-11e7-8988-f63123b038c1.png)
산책

![festival](https://cloud.githubusercontent.com/assets/26480592/24836959/f0f50316-1d63-11e7-823e-6f67df23e367.png)
festival

**Comment by Daemin** [comment]
### 회원가입
![address](https://cloud.githubusercontent.com/assets/26480633/24861381/85973f5a-1e33-11e7-9bc8-4891c4c30aaf.PNG)
![email](https://cloud.githubusercontent.com/assets/26480633/24861382/86701d34-1e33-11e7-93c8-cd75f2801cd5.PNG)
![id](https://cloud.githubusercontent.com/assets/26480633/24861385/87424084-1e33-11e7-8684-0e39cd962ced.PNG)
![name](https://cloud.githubusercontent.com/assets/26480633/24861386/8835a9a4-1e33-11e7-80b0-4f9de9b75199.PNG)
![nickname](https://cloud.githubusercontent.com/assets/26480633/24861387/89004ce0-1e33-11e7-8798-f627b2cb9946.PNG)
![password](https://cloud.githubusercontent.com/assets/26480633/24861388/89d3a446-1e33-11e7-9c1f-deff0f533efc.PNG)

**Comment by jwKim1835** [comment]
형님들 앱 디자인은 기획 말고 스마트폰[개발]에 이슈하나 만들어 놓을테니 거기다 올려주세요
앱 기획은 끝났으니까 디자인과 개발부분인데 이걸 설계부분에 올리는건 맞지않다고 생각합니다
제가 만들어 둘께요

**Comment by jwKim1835** [comment]
지금 앱 기획 부분은 끝이 났으니 이 이슈는 닫도록 하겠습니다.
