### ISSUE TITLE
데이터베이스 설계

### ISSUE THREAD

**Issue by jwKim1835** [201733cpb1/OurCompany#4]

**Comment by 94ljy** [comment]
# 아두이노
 * 상태체크

 * 활동량

 * 온도

 * 예방접종 주기

 * 식사 주기

 * 심박수

# 안드로이드
 * 회원
 * ID
 * PS
 * Email
 * 이름
 * 닉네임

# 홈
 * 강아지 프로필 사진
 * 밥 주기
 * 산책횟수

 # 펫 추가
 * 동물 종류
 * 동물 이름
 * 출생일
 * 성별
 * 제품넘버

# 예방접종
 * 회차
 * 받은날(회차에 해당하는 날짜 - 받은 날짜)
 * 자가진단리스트

# 펫 시터 등록
 * 등록자
 * 주소
 * 몇 마리
 * 특이사항
 * 해당하는 개 종류

# 펫 시터 조회
 * 등록된 정보 출력

# 팁 게시판
 * 글번호
 * 제목
 * 글쓴이
 * 날짜
 * 조회수
 * 추천
 * 글내용

# 중고 장터
 * 카테고리
 * 제목
 * 가격
 * 작성자
 * 내용
 * 작성 날짜
 * 신고
 * 판매자 정보
 * 댓글
 * 전화번호
 * 거래 지역
 * 택배비 포함여부

**Comment by jwKim1835** [comment]
# 아두이노
 * ~~상태체크~~

 * ~~활동량~~

 * ~~온도~~

 * ~~예방접종 주기~~

 * ~~식사 주기~~

 * ~~심박수~~

# 안드로이드
 * ~~회원~~
 * ~~ID~~
 * ~~PS~~
 * ~~Email~~
 * ~~이름~~
 * ~~닉네임~~

# 홈
 * ~~강아지 프로필 사진~~
 * ~~밥 주기~~
 * ~~산책횟수~~

 # 펫 추가
 * ~~동물 종류~~
 * ~~동물 이름~~
 * ~~출생일~~
 * ~~성별~~
 * ~~제품넘버~~

# 예방접종
 * ~~회차~~
 * ~~받은날(회차에 해당하는 날짜 - 받은 날짜)~~

# 자가진단리스트
* ~~설계~~(완료)

# 펫 시터 등록
 * 등록자
 * 주소
 * 몇 마리
 * 특이사항
 * 해당하는 개 종류

# 펫 시터 조회
 * 등록된 정보 출력

# 팁 게시판
 * 글번호
 * 제목
 * 글쓴이
 * 날짜
 * 조회수
 * 추천
 * 글내용

# 중고 장터
 * 카테고리
 * 제목
 * 가격
 * 작성자
 * 내용
 * 작성 날짜
 * 신고
 * 판매자 정보
 * 댓글
 * 전화번호
 * 거래 지역
 * 택배비 포함여부

**Comment by jwKim1835** [comment]
![image](https://cloud.githubusercontent.com/assets/26519770/24288535/1727ff98-10c1-11e7-96be-721f8443f47d.png)

**Comment by jwKim1835** [comment]
# 아두이노
 * ~~상태체크~~

 * ~~활동량~~

 * ~~온도~~

 * ~~예방접종 주기~~

 * ~~식사 주기~~

 * ~~심박수~~

# 안드로이드
 * ~~회원~~
 * ~~ID~~
 * ~~PS~~
 * ~~Email~~
 * ~~이름~~
 * ~~닉네임~~

# 홈
 * ~~강아지 프로필 사진~~
 * ~~밥 주기~~
 * ~~산책횟수~~

 # 펫 추가
 * ~~동물 종류~~
 * ~~동물 이름~~
 * ~~출생일~~
 * ~~성별~~
 * ~~제품넘버~~

# 예방접종
 * ~~회차~~
 * ~~받은날(회차에 해당하는 날짜 - 받은 날짜)~~

# 자가진단리스트
* ~~설계~~(완료)

# 펫 시터 등록 / 참조
 * ~~등록자~~
 * ~~주소~~
 * ~~몇 마리~~
 * ~~특이사항~~
 * ~~해당하는 개 종류~~
![image](https://cloud.githubusercontent.com/assets/26519770/24289293/fa788e32-10c3-11e7-94e4-1bed7edf9cd7.png)

# 팁 게시판
 * 글번호
 * 제목
 * 글쓴이
 * 날짜
 * 조회수
 * 추천
 * 글내용

# 중고 장터
 * 카테고리
 * 제목
 * 가격
 * 작성자
 * 내용
 * 작성 날짜
 * 신고
 * 판매자 정보
 * 댓글
 * 전화번호
 * 거래 지역
 * 택배비 포함여부

**Comment by jwKim1835** [comment]
# 아두이노
 * ~~상태체크~~

 * ~~활동량~~

 * ~~온도~~

 * ~~예방접종 주기~~

 * ~~식사 주기~~

 * ~~심박수~~

# 안드로이드
 * ~~회원~~
 * ~~ID~~
 * ~~PS~~
 * ~~Email~~
 * ~~이름~~
 * ~~닉네임~~

# 홈
 * ~~강아지 프로필 사진~~
 * ~~밥 주기~~
 * ~~산책횟수~~

 # 펫 추가
 * ~~동물 종류~~
 * ~~동물 이름~~
 * ~~출생일~~
 * ~~성별~~
 * ~~제품넘버~~

# 예방접종
 * ~~회차~~
 * ~~받은날(회차에 해당하는 날짜 - 받은 날짜)~~

# 자가진단리스트
* ~~설계~~(완료)

# 펫 시터 등록 / 참조
 * ~~등록자~~
 * ~~주소~~
 * ~~몇 마리~~
 * ~~특이사항~~
 * ~~해당하는 개 종류~~

# 팁 게시판
 * ~~글번호~~
 * ~~제목~~
 * ~~글쓴이~~
 * ~~날짜~~
 * ~~조회수~~
 * ~~추천~~
 * ~~글내용~~

# 중고 장터
 * ~~카테고리~~
 * ~~제목~~
 * ~~가격~~
 * ~~작성자~~
 * ~~내용~~
 * ~~작성 날짜~~
 * ~~신고~~
 * ~~판매자 정보~~
 * ~~댓글~~
 * ~~전화번호~~
 * ~~거래 지역~~
 * ~~택배비 포함여부~~
![image](https://cloud.githubusercontent.com/assets/26519770/24352243/c9be3b9a-1323-11e7-897d-7354313d39ce.png)

# SNS

**Comment by jwKim1835** [comment]
# 최종 DB설계
![image](https://cloud.githubusercontent.com/assets/26519770/24541037/c168d5c6-1630-11e7-80a2-582ee00bab40.png)

**Comment by 94ljy** [comment]
DB 2017/03/31 설계 완료 (추후 문제점 발견시 수정 예정)

**Comment by jwKim1835** [comment]
# 재 설계
![image](https://cloud.githubusercontent.com/assets/26519770/24600409/7c465ee4-188f-11e7-994c-ada877fdae3f.png)

**Comment by jwKim1835** [comment]
# 설계 수정
![image](https://cloud.githubusercontent.com/assets/26519770/24602229/e4195f6a-1896-11e7-9b9b-bc1cabec8a88.png)

**Comment by 94ljy** [comment]
# 설계 수정2

![db](https://cloud.githubusercontent.com/assets/22091605/24852301/f13ac532-1e11-11e7-95e3-cc02f2cef7c5.PNG)

**Comment by jwKim1835** [comment]
![default](https://cloud.githubusercontent.com/assets/26519770/25114138/5eedc8ec-2437-11e7-886d-1da5db2e0789.PNG)

데이터베이스 속성명 수정

**Comment by KimJoungWoo** [comment]
AnimalCondition 테이블 수정
CheckTime의 자료형 Time으로 지정
CheckDate속성 추가 Date자료형으로 지정

**Comment by jwKim1835** [comment]
BoardTable
View -> Visit
Like -> Good
으로 속성명을 수정 바랍니다.

**Comment by 94ljy** [comment]
![default](https://cloud.githubusercontent.com/assets/22091605/25276255/4265c3d8-26d4-11e7-93b4-1ca55bd0e5db.PNG)
[MyProject.zip](https://github.com/201733cpb1/OurCompany/files/946943/MyProject.zip)

**Comment by 94ljy** [comment]
![rewtt](https://cloud.githubusercontent.com/assets/22091605/25955780/1d1bd33e-36a5-11e7-9438-c4ffabff7ca8.PNG)

주소 부분 수정

**Comment by 94ljy** [comment]
[MyProject.zip](https://github.com/201733cpb1/OurCompany/files/993417/MyProject.zip)
