### ISSUE TITLE
발표자료

### ISSUE THREAD

**Issue by jwKim1835** [201733cpb1/OurCompany#8]

**Comment by jwKim1835** [comment]
앱 UI ppt
[디자인 17-03-21.pptx](https://github.com/201733cpb1/OurCompany/files/872217/17-03-21.pptx)

**Comment by jwKim1835** [comment]
3/24 안드로이드 발표자료 ppt
[My Love Pet.pptx](https://github.com/201733cpb1/OurCompany/files/872221/My.Love.Pet.pptx)

**Comment by jwKim1835** [comment]
3/27 발표자료 수정
[My Love Pet(수정).pptx](https://github.com/201733cpb1/OurCompany/files/872224/My.Love.Pet.pptx)

**Comment by 94ljy** [comment]
3/27 발표자료 디자인 수정
[My Love Pet(디자인 수정).pptx](https://github.com/201733cpb1/OurCompany/files/872458/My.Love.Pet.pptx)

**Comment by 94ljy** [comment]
3/28 발표자료 수정
[My Love Pet(디자인 수정).pptx](https://github.com/201733cpb1/OurCompany/files/875361/My.Love.Pet.pptx)

**Comment by 94ljy** [comment]
3/28 발표자료 수정 2차
[My Love Pet(디자인 수정).pptx](https://github.com/201733cpb1/OurCompany/files/875413/My.Love.Pet.pptx)

**Comment by jwKim1835** [comment]
[My.Love.Pet.pptx](https://github.com/201733cpb1/OurCompany/files/881654/My.Love.Pet.pptx)

**Comment by jwKim1835** [comment]
기획 발표용 ppt는 이제 작성이 끝났으니까 지금 이슈는 닫아놓을께요 중간 발표할 때 다시 이 이슈 열어서 ppt작업을 업로드 하면 되겠습니다.

**Comment by 94ljy** [comment]
Ok

**Comment by Daemin** [comment]
그렇게하자~ 고생했음

**Comment by jjonghun1004** [comment]
good!
